// ScoutCopilot — Mock comparison data

import type { MockComparisonPlayer } from './types'

export const comparisonPlayers: MockComparisonPlayer[] = [
  {
    id: 'cp1',
    name: 'Kwame Asante',
    club: 'Northgate United',
    position: 'LW / CF',
    age: 28,
    nationality: 'Ghana',
    image: '/avatars/player-11.webp',
    metrics: { 'Goals/90': 0.68, 'Assists/90': 0.12, 'Pass %': 81.4, 'Tackles/90': 1.2, 'Interceptions/90': 0.3, 'xG/90': 0.62, 'Key Passes/90': 1.8, 'Aerial Won %': 48.2, 'Dribbles/90': 3.1, 'Prog. Carries/90': 5.4 },
    radarData: [
      { label: 'Shooting', value: 85 },
      { label: 'Passing', value: 68 },
      { label: 'Dribbling', value: 78 },
      { label: 'Physical', value: 82 },
      { label: 'Defending', value: 45 },
      { label: 'Speed', value: 90 },
    ],
  },
  {
    id: 'cp2',
    name: 'Gonçalo Pinto',
    club: 'AC Stellare',
    position: 'LW / CF',
    age: 27,
    nationality: 'Portugal',
    image: '/avatars/player-4.webp',
    metrics: { 'Goals/90': 0.45, 'Assists/90': 0.34, 'Pass %': 76.8, 'Tackles/90': 0.4, 'Interceptions/90': 0.6, 'xG/90': 0.48, 'Key Passes/90': 2.4, 'Aerial Won %': 31.5, 'Dribbles/90': 4.2, 'Prog. Carries/90': 7.1 },
    radarData: [
      { label: 'Shooting', value: 72 },
      { label: 'Passing', value: 74 },
      { label: 'Dribbling', value: 92 },
      { label: 'Physical', value: 76 },
      { label: 'Defending', value: 30 },
      { label: 'Speed', value: 88 },
    ],
  },
  {
    id: 'cp3',
    name: 'Marco Lindström',
    club: 'FC Nordhavn',
    position: 'LB / LWB',
    age: 25,
    nationality: 'Sweden',
    image: '/avatars/player-1.webp',
    metrics: { 'Goals/90': 0.04, 'Assists/90': 0.17, 'Pass %': 89.2, 'Tackles/90': 2.8, 'Interceptions/90': 1.4, 'xG/90': 0.12, 'Key Passes/90': 1.4, 'Aerial Won %': 42.0, 'Dribbles/90': 3.4, 'Prog. Carries/90': 8.2 },
    radarData: [
      { label: 'Shooting', value: 38 },
      { label: 'Passing', value: 78 },
      { label: 'Dribbling', value: 82 },
      { label: 'Physical', value: 71 },
      { label: 'Defending', value: 68 },
      { label: 'Speed', value: 95 },
    ],
  },
  {
    id: 'cp4',
    name: 'Enzo Valenti',
    club: 'Crescent Athletic',
    position: 'LB / LM',
    age: 23,
    nationality: 'Italy',
    image: '/avatars/player-2.webp',
    metrics: { 'Goals/90': 0.04, 'Assists/90': 0.22, 'Pass %': 85.1, 'Tackles/90': 3.1, 'Interceptions/90': 1.6, 'xG/90': 0.08, 'Key Passes/90': 1.6, 'Aerial Won %': 52.4, 'Dribbles/90': 2.2, 'Prog. Carries/90': 6.7 },
    radarData: [
      { label: 'Shooting', value: 32 },
      { label: 'Passing', value: 82 },
      { label: 'Dribbling', value: 68 },
      { label: 'Physical', value: 78 },
      { label: 'Defending', value: 80 },
      { label: 'Speed', value: 82 },
    ],
  },
  {
    id: 'cp5',
    name: 'Dani Cortez',
    club: 'Atlético Ronda',
    position: 'LB / RB',
    age: 22,
    nationality: 'Spain',
    image: '/avatars/player-3.webp',
    metrics: { 'Goals/90': 0.02, 'Assists/90': 0.14, 'Pass %': 87.6, 'Tackles/90': 2.6, 'Interceptions/90': 2.1, 'xG/90': 0.05, 'Key Passes/90': 1.1, 'Aerial Won %': 55.8, 'Dribbles/90': 1.9, 'Prog. Carries/90': 7.1 },
    radarData: [
      { label: 'Shooting', value: 28 },
      { label: 'Passing', value: 85 },
      { label: 'Dribbling', value: 64 },
      { label: 'Physical', value: 74 },
      { label: 'Defending', value: 82 },
      { label: 'Speed', value: 78 },
    ],
  },
  {
    id: 'cp6',
    name: 'Ousmane Diallo',
    club: 'Inter Azzurra',
    position: 'CF / LW',
    age: 28,
    nationality: 'Senegal',
    image: '/avatars/player-15.webp',
    metrics: { 'Goals/90': 0.57, 'Assists/90': 0.18, 'Pass %': 81.4, 'Tackles/90': 0.6, 'Interceptions/90': 0.2, 'xG/90': 0.52, 'Key Passes/90': 1.4, 'Aerial Won %': 38.0, 'Dribbles/90': 2.8, 'Prog. Carries/90': 4.1 },
    radarData: [
      { label: 'Shooting', value: 88 },
      { label: 'Passing', value: 65 },
      { label: 'Dribbling', value: 82 },
      { label: 'Physical', value: 78 },
      { label: 'Defending', value: 32 },
      { label: 'Speed', value: 92 },
    ],
  },
  {
    id: 'cp7',
    name: 'Samir Benali',
    club: 'Midland Rovers',
    position: 'LB / LWB',
    age: 23,
    nationality: 'Algeria',
    image: '/avatars/player-7.webp',
    metrics: { 'Goals/90': 0.03, 'Assists/90': 0.15, 'Pass %': 83.7, 'Tackles/90': 2.4, 'Interceptions/90': 1.2, 'xG/90': 0.07, 'Key Passes/90': 1.3, 'Aerial Won %': 48.6, 'Dribbles/90': 2.3, 'Prog. Carries/90': 6.2 },
    radarData: [
      { label: 'Shooting', value: 30 },
      { label: 'Passing', value: 76 },
      { label: 'Dribbling', value: 72 },
      { label: 'Physical', value: 80 },
      { label: 'Defending', value: 76 },
      { label: 'Speed', value: 84 },
    ],
  },
  {
    id: 'cp8',
    name: 'Nicolás Herrera',
    club: 'AS Roma Rossa',
    position: 'RW / AM',
    age: 23,
    nationality: 'Argentina',
    image: '/avatars/player-18.webp',
    metrics: { 'Goals/90': 0.33, 'Assists/90': 0.38, 'Pass %': 83.1, 'Tackles/90': 0.8, 'Interceptions/90': 0.5, 'xG/90': 0.28, 'Key Passes/90': 2.4, 'Aerial Won %': 28.0, 'Dribbles/90': 4.8, 'Prog. Carries/90': 6.2 },
    radarData: [
      { label: 'Shooting', value: 68 },
      { label: 'Passing', value: 80 },
      { label: 'Dribbling', value: 94 },
      { label: 'Physical', value: 58 },
      { label: 'Defending', value: 28 },
      { label: 'Speed', value: 90 },
    ],
  },
]

