// ScoutCopilot — Mock player report data

import type { MockPlayerReport } from './types'

export const playerReports: Record<string, MockPlayerReport> = {
  p1: {
    playerId: 'p1',
    playerName: 'Marco Lindström',
    age: 25,
    nationality: 'Sweden',
    position: 'LB / LWB',
    club: 'FC Nordhavn',
    league: 'Bundesliga',
    image: '/avatars/player-1.webp',
    summary: 'Lindström continues to be one of the most dynamic full-backs in European football. His ability to transition from defense to attack at high speed is elite-level. While his tactical positioning has improved significantly, he remains most effective when allowed to overlap and drive into the final third. His progressive carrying numbers rank in the 97th percentile among all European full-backs.',
    strengths: [
      'Elite recovery speed and acceleration',
      'Ball progression and carrying ability',
      'One-on-one defending in wide areas',
      'Crossing accuracy from deep positions',
      'Press resistance under pressure',
    ],
    weaknesses: [
      'Aerial duels (height disadvantage)',
      'Final third decision-making under pressure',
      'Positional discipline when caught high',
    ],
    styleOfPlay: 'An explosive, attacking full-back who functions as a secondary winger in possession phases. Lindström creates width and stretches opposition defensive lines through pace and direct running. In defensive transitions, his recovery speed compensates for his high starting position. Best deployed in systems that encourage full-back overlaps with inside-cutting wingers.',
    recommendation: 'monitor',
    fitScore: 94,
    seasonStats: {
      Appearances: 28, Goals: 1, Assists: 4, Minutes: 2140,
      'Pass Accuracy': '89.2%', 'Tackles Won': 34, Interceptions: 18,
      'Prog. Carries/90': 8.2, 'Key Passes/90': 1.4, 'Aerial Duels Won': '42%',
    },
    radarData: [
      { label: 'Speed', value: 95, average: 68 }, { label: 'Passing', value: 78, average: 72 },
      { label: 'Dribbling', value: 82, average: 58 }, { label: 'Physical', value: 71, average: 70 },
      { label: 'Defending', value: 68, average: 74 }, { label: 'Crossing', value: 74, average: 65 },
    ],
    similarPlayers: [
      { playerId: 'p4', name: 'Tiago Noronha', club: 'AS Lumière', age: 24, similarity: 94, image: '/avatars/player-4.webp' },
      { playerId: 'p3', name: 'Dani Cortez', club: 'Atlético Ronda', age: 22, similarity: 91, image: '/avatars/player-3.webp' },
      { playerId: 'p2', name: 'Enzo Valenti', club: 'Crescent Athletic', age: 23, similarity: 88, image: '/avatars/player-2.webp' },
    ],
    transferHistory: [
      { club: 'FC Nordhavn', date: 'Jan 2023', fee: '€10.00m' },
      { club: 'IFK Malmköping', date: 'Youth', fee: 'Academy' },
    ],
    contractInfo: { value: '€70.00m', until: 'June 30, 2027', wage: '€175k/week', agent: 'Nordic Sports Group' },
  },
  p2: {
    playerId: 'p2',
    playerName: 'Enzo Valenti',
    age: 23,
    nationality: 'Italy',
    position: 'LB / LM',
    club: 'Crescent Athletic',
    league: 'Premier League',
    image: '/avatars/player-2.webp',
    summary: 'Valenti is a technically gifted full-back who combines Italian defensive discipline with modern attacking output. His reading of the game allows him to intercept passes in advanced areas and quickly transition into attack. Particularly effective in build-up play, he offers a calm passing option under pressure and consistently finds progressive channels.',
    strengths: [
      'Exceptional passing range from deep',
      'Tactical intelligence and positioning',
      'Composure under high press',
      'Set-piece delivery from the left',
    ],
    weaknesses: [
      'Pace in recovery runs against quick wingers',
      'Physicality in aerial duels',
      'Tendency to drift too central in possession',
    ],
    styleOfPlay: 'A technically refined full-back who operates as an inverted defender in build-up phases. Valenti is most dangerous when he drifts inside to create overloads in central midfield. His vision and weight of pass make him a key creator from deep. Best utilized in possession-heavy systems that demand full-backs to contribute to midfield control.',
    recommendation: 'sign',
    fitScore: 88,
    seasonStats: {
      Appearances: 31, Goals: 0, Assists: 7, Minutes: 2580,
      'Pass Accuracy': '85.1%', 'Tackles Won': 41, Interceptions: 24,
      'Prog. Carries/90': 6.7, 'Key Passes/90': 1.8, 'Aerial Duels Won': '38%',
    },
    radarData: [
      { label: 'Speed', value: 72, average: 68 }, { label: 'Passing', value: 88, average: 72 },
      { label: 'Dribbling', value: 74, average: 58 }, { label: 'Physical', value: 65, average: 70 },
      { label: 'Defending', value: 78, average: 74 }, { label: 'Crossing', value: 80, average: 65 },
    ],
    similarPlayers: [
      { playerId: 'p1', name: 'Marco Lindström', club: 'FC Nordhavn', age: 25, similarity: 88, image: '/avatars/player-1.webp' },
      { playerId: 'p5', name: 'Rémi Blanchard', club: 'Olympique Azur', age: 23, similarity: 82, image: '/avatars/player-5.webp' },
      { playerId: 'p9', name: 'Stijn de Graaf', club: 'Harton Villa', age: 24, similarity: 79, image: '/avatars/player-9.webp' },
    ],
    transferHistory: [
      { club: 'Crescent Athletic', date: 'Aug 2024', fee: '€14.50m' },
      { club: 'Genoa CFC Rossoblu', date: 'Jul 2021', fee: '€3.20m' },
      { club: 'Atalanta Youth', date: 'Youth', fee: 'Academy' },
    ],
    contractInfo: { value: '€45.00m', until: 'June 30, 2029', wage: '€95k/week', agent: 'Stellar Group' },
  },
  p3: {
    playerId: 'p3',
    playerName: 'Dani Cortez',
    age: 22,
    nationality: 'Spain',
    position: 'LB / RB',
    club: 'Atlético Ronda',
    league: 'La Liga',
    image: '/avatars/player-3.webp',
    summary: 'Cortez is a versatile defender capable of operating on either flank. His tactical awareness belies his age, and his ability to read the game makes him effective in both low-block and high-pressing systems. While his attacking output is modest, his defensive reliability and positional discipline make him a valuable squad asset with significant upside.',
    strengths: [
      'Versatility across both full-back positions',
      'Outstanding positional discipline',
      'Strong in 1v1 defensive situations',
      'Reliable passing under pressure',
    ],
    weaknesses: [
      'Limited attacking threat in final third',
      'Crossing accuracy needs improvement',
      'Can be caught ball-watching on set pieces',
    ],
    styleOfPlay: 'A defensively-minded full-back who prioritizes structure over adventure. Cortez excels at maintaining the back line shape and covering for attacking teammates. His two-footed ability allows seamless switching between flanks. Ideal for managers who want their full-backs to provide width without gambling on overlaps.',
    recommendation: 'monitor',
    fitScore: 76,
    seasonStats: {
      Appearances: 26, Goals: 0, Assists: 2, Minutes: 2080,
      'Pass Accuracy': '87.6%', 'Tackles Won': 48, Interceptions: 31,
      'Prog. Carries/90': 7.1, 'Key Passes/90': 0.8, 'Aerial Duels Won': '52%',
    },
    radarData: [
      { label: 'Speed', value: 74, average: 68 }, { label: 'Passing', value: 80, average: 72 },
      { label: 'Dribbling', value: 62, average: 58 }, { label: 'Physical', value: 76, average: 70 },
      { label: 'Defending', value: 84, average: 74 }, { label: 'Crossing', value: 58, average: 65 },
    ],
    similarPlayers: [
      { playerId: 'p6', name: 'Bálint Varga', club: 'Southport City', age: 22, similarity: 90, image: '/avatars/player-6.webp' },
      { playerId: 'p12', name: 'Emre Demir', club: 'Coastal FC', age: 25, similarity: 85, image: '/avatars/player-12.webp' },
      { playerId: 'p8', name: 'Pablo Navarro', club: 'Sporting Castilla', age: 23, similarity: 83, image: '/avatars/player-8.webp' },
    ],
    transferHistory: [
      { club: 'Atlético Ronda', date: 'Jul 2024', fee: '€8.00m' },
      { club: 'Sevilla B', date: 'Youth', fee: 'Academy' },
    ],
    contractInfo: { value: '€25.00m', until: 'June 30, 2028', wage: '€55k/week', agent: 'Bahía Sports Management' },
  },
  p4: {
    playerId: 'p4',
    playerName: 'Tiago Noronha',
    age: 24,
    nationality: 'Portugal',
    position: 'LB',
    club: 'AS Lumière',
    league: 'Ligue 1',
    image: '/avatars/player-4.webp',
    summary: 'Noronha is a dynamic attacking full-back in the Portuguese tradition. His dribbling ability and close control in tight spaces make him exceptionally difficult to press. He consistently beats his man on the outside and delivers dangerous crosses into the box. His defensive work rate has improved markedly this season under a more structured tactical system.',
    strengths: [
      'Outstanding dribbling and ball control',
      'Dangerous crossing from wide areas',
      'Excellent work rate in both phases',
      'Progressive carrying through midfield lines',
    ],
    weaknesses: [
      'Decision-making in the final third',
      'Concentration lapses in defensive transitions',
      'Struggles against physical wingers',
    ],
    styleOfPlay: 'A technical, overlapping full-back who thrives when given license to attack. His dribbling ability allows him to create numerical advantages in wide areas. His delivery from crossing positions is consistently dangerous. Needs a disciplined midfield behind him to cover his advanced positioning.',
    recommendation: 'sign',
    fitScore: 82,
    seasonStats: {
      Appearances: 30, Goals: 2, Assists: 5, Minutes: 2410,
      'Pass Accuracy': '84.3%', 'Tackles Won': 29, Interceptions: 15,
      'Prog. Carries/90': 7.9, 'Key Passes/90': 1.6, 'Aerial Duels Won': '35%',
    },
    radarData: [
      { label: 'Speed', value: 84, average: 68 }, { label: 'Passing', value: 76, average: 72 },
      { label: 'Dribbling', value: 88, average: 58 }, { label: 'Physical', value: 68, average: 70 },
      { label: 'Defending', value: 62, average: 74 }, { label: 'Crossing', value: 82, average: 65 },
    ],
    similarPlayers: [
      { playerId: 'p1', name: 'Marco Lindström', club: 'FC Nordhavn', age: 25, similarity: 94, image: '/avatars/player-1.webp' },
      { playerId: 'p7', name: 'Samir Benali', club: 'Midland Rovers', age: 23, similarity: 86, image: '/avatars/player-7.webp' },
      { playerId: 'p11', name: 'Adrien Morel', club: 'AC Stellare', age: 28, similarity: 81, image: '/avatars/player-11.webp' },
    ],
    transferHistory: [
      { club: 'AS Lumière', date: 'Jan 2025', fee: '€12.00m' },
      { club: 'SC Braga B', date: 'Jul 2022', fee: '€2.80m' },
      { club: 'Sporting CP Youth', date: 'Youth', fee: 'Academy' },
    ],
    contractInfo: { value: '€38.00m', until: 'June 30, 2029', wage: '€72k/week', agent: 'Gestifute International' },
  },
  p5: {
    playerId: 'p5',
    playerName: 'Rémi Blanchard',
    age: 23,
    nationality: 'France',
    position: 'LB / LM',
    club: 'Olympique Azur',
    league: 'Ligue 1',
    image: '/avatars/player-5.webp',
    summary: 'Blanchard is a developing full-back with significant raw potential but inconsistent performances. His athletic profile is outstanding but his technical and tactical development has lagged. Shows flashes of brilliance in attacking phases but defensive lapses remain too frequent for a top-flight defender. A project player who needs time and coaching.',
    strengths: [
      'Explosive acceleration and top speed',
      'Strong aerial presence for a full-back',
      'Willingness to commit to challenges',
    ],
    weaknesses: [
      'Poor crossing accuracy and final ball',
      'Inconsistent decision-making under pressure',
      'Positional discipline needs significant work',
      'Struggles with quick combination play',
    ],
    styleOfPlay: 'An athletic full-back who relies on physicality and pace rather than technical ability. Blanchard is effective in transition-based systems where his speed can be utilized. His defensive work is committed but often poorly timed. Requires a patient coaching environment to develop his weaker areas.',
    recommendation: 'pass',
    fitScore: 54,
    seasonStats: {
      Appearances: 18, Goals: 0, Assists: 1, Minutes: 1290,
      'Pass Accuracy': '81.0%', 'Tackles Won': 22, Interceptions: 11,
      'Prog. Carries/90': 4.3, 'Key Passes/90': 0.5, 'Aerial Duels Won': '58%',
    },
    radarData: [
      { label: 'Speed', value: 90, average: 68 }, { label: 'Passing', value: 58, average: 72 },
      { label: 'Dribbling', value: 52, average: 58 }, { label: 'Physical', value: 85, average: 70 },
      { label: 'Defending', value: 60, average: 74 }, { label: 'Crossing', value: 45, average: 65 },
    ],
    similarPlayers: [
      { playerId: 'p10', name: 'Mateo Rivas', club: 'Miami Coast FC', age: 19, similarity: 78, image: '/avatars/player-10.webp' },
      { playerId: 'p6', name: 'Bálint Varga', club: 'Southport City', age: 22, similarity: 72, image: '/avatars/player-6.webp' },
      { playerId: 'p8', name: 'Pablo Navarro', club: 'Sporting Castilla', age: 23, similarity: 68, image: '/avatars/player-8.webp' },
    ],
    transferHistory: [
      { club: 'Olympique Azur', date: 'Jul 2024', fee: '€4.50m' },
      { club: 'Toulouse FC', date: 'Youth', fee: 'Academy' },
    ],
    contractInfo: { value: '€12.00m', until: 'June 30, 2028', wage: '€28k/week', agent: 'Sport Cover Agency' },
  },
  p6: {
    playerId: 'p6',
    playerName: 'Bálint Varga',
    age: 22,
    nationality: 'Hungary',
    position: 'LB',
    club: 'Southport City',
    league: 'Premier League',
    image: '/avatars/player-6.webp',
    summary: 'Varga has adapted impressively to Premier League football since his move from Budapest. A disciplined defender who rarely gets caught out of position, he provides consistent performances without spectacular highs or lows. His steady improvement trajectory and young age make him an interesting prospect for clubs seeking defensive reliability.',
    strengths: [
      'Excellent defensive positioning',
      'Strong in tackles and ground duels',
      'Consistent performance level',
      'Good awareness of space behind him',
    ],
    weaknesses: [
      'Limited creativity in attacking phases',
      'Crossing delivery is predictable',
      'Can be overly cautious with forward passing',
    ],
    styleOfPlay: 'A defensive full-back who prioritizes solidity over flair. Varga is the type of defender who quietly accumulates clean sheets through intelligent positioning rather than heroic last-ditch tackles. His progressive output is modest but his defensive contributions are well above average for his age group.',
    recommendation: 'monitor',
    fitScore: 79,
    seasonStats: {
      Appearances: 24, Goals: 0, Assists: 1, Minutes: 1920,
      'Pass Accuracy': '82.4%', 'Tackles Won': 52, Interceptions: 28,
      'Prog. Carries/90': 5.8, 'Key Passes/90': 0.6, 'Aerial Duels Won': '55%',
    },
    radarData: [
      { label: 'Speed', value: 70, average: 68 }, { label: 'Passing', value: 72, average: 72 },
      { label: 'Dribbling', value: 55, average: 58 }, { label: 'Physical', value: 78, average: 70 },
      { label: 'Defending', value: 82, average: 74 }, { label: 'Crossing', value: 56, average: 65 },
    ],
    similarPlayers: [
      { playerId: 'p3', name: 'Dani Cortez', club: 'Atlético Ronda', age: 22, similarity: 90, image: '/avatars/player-3.webp' },
      { playerId: 'p8', name: 'Pablo Navarro', club: 'Sporting Castilla', age: 23, similarity: 84, image: '/avatars/player-8.webp' },
      { playerId: 'p12', name: 'Emre Demir', club: 'Coastal FC', age: 25, similarity: 80, image: '/avatars/player-12.webp' },
    ],
    transferHistory: [
      { club: 'Southport City', date: 'Aug 2025', fee: '€6.50m' },
      { club: 'Ferencváros TC', date: 'Jul 2022', fee: '€1.20m' },
      { club: 'MTK Budapest', date: 'Youth', fee: 'Academy' },
    ],
    contractInfo: { value: '€18.00m', until: 'June 30, 2030', wage: '€42k/week', agent: 'ISM Sport' },
  },
  p7: {
    playerId: 'p7',
    playerName: 'Samir Benali',
    age: 23,
    nationality: 'Algeria',
    position: 'LB / LWB',
    club: 'Midland Rovers',
    league: 'Premier League',
    image: '/avatars/player-7.webp',
    summary: 'Benali is a technically accomplished wing-back who has flourished in a back-three system. His ability to beat defenders 1v1 and deliver quality final balls makes him a genuine attacking asset. Defensively, he has shown improvement in awareness and tracking runners, though he remains best suited to systems where he operates as a wing-back rather than a traditional full-back.',
    strengths: [
      'Exceptional 1v1 dribbling ability',
      'Quality crossing from advanced positions',
      'Intelligent movement off the ball',
      'Good link-up play with wide forwards',
    ],
    weaknesses: [
      'Defensive vulnerability in a back-four',
      'Stamina management over 90 minutes',
      'Susceptible to quick counter-attacks',
    ],
    styleOfPlay: 'An attack-minded wing-back who functions as a wide playmaker in the final third. His skill on the ball and crossing ability make him a primary creative outlet from the left flank. He requires a system that provides defensive cover behind him, ideally a back-three or a holding midfielder who can cover the left channel.',
    recommendation: 'sign',
    fitScore: 85,
    seasonStats: {
      Appearances: 27, Goals: 3, Assists: 6, Minutes: 2160,
      'Pass Accuracy': '83.7%', 'Tackles Won': 26, Interceptions: 14,
      'Prog. Carries/90': 6.2, 'Key Passes/90': 2.1, 'Aerial Duels Won': '32%',
    },
    radarData: [
      { label: 'Speed', value: 82, average: 68 }, { label: 'Passing', value: 80, average: 72 },
      { label: 'Dribbling', value: 86, average: 58 }, { label: 'Physical', value: 67, average: 70 },
      { label: 'Defending', value: 58, average: 74 }, { label: 'Crossing', value: 84, average: 65 },
    ],
    similarPlayers: [
      { playerId: 'p4', name: 'Tiago Noronha', club: 'AS Lumière', age: 24, similarity: 91, image: '/avatars/player-4.webp' },
      { playerId: 'p11', name: 'Adrien Morel', club: 'AC Stellare', age: 28, similarity: 85, image: '/avatars/player-11.webp' },
      { playerId: 'p1', name: 'Marco Lindström', club: 'FC Nordhavn', age: 25, similarity: 82, image: '/avatars/player-1.webp' },
    ],
    transferHistory: [
      { club: 'Midland Rovers', date: 'Jan 2025', fee: '€11.00m' },
      { club: 'USM Alger', date: 'Jul 2021', fee: '€0.80m' },
    ],
    contractInfo: { value: '€32.00m', until: 'June 30, 2029', wage: '€65k/week', agent: 'CAA Stellar' },
  },
  p8: {
    playerId: 'p8',
    playerName: 'Pablo Navarro',
    age: 23,
    nationality: 'Spain',
    position: 'LB',
    club: 'Sporting Castilla',
    league: 'La Liga',
    image: '/avatars/player-8.webp',
    summary: 'Navarro is a solid, no-nonsense full-back who embodies the traditional Spanish defensive school. His positioning and reading of the game are mature beyond his years. While he lacks the flair of some modern attacking full-backs, his consistency and reliability make him a dependable option in a well-organized defensive unit.',
    strengths: [
      'Excellent reading of the game',
      'Reliable in defensive duels',
      'Strong communicator on the pitch',
      'Consistent passing accuracy',
    ],
    weaknesses: [
      'Lacks pace against top-level wingers',
      'Limited contribution in the final third',
      'Set-piece positioning could improve',
    ],
    styleOfPlay: 'A classically trained Spanish defender who values positional play above all else. Navarro is effective in possession-based systems where the tempo is controlled. His defensive intelligence allows the centre-backs to push higher, knowing the left flank is well-covered. Not suited to high-intensity transition football.',
    recommendation: 'monitor',
    fitScore: 73,
    seasonStats: {
      Appearances: 25, Goals: 0, Assists: 2, Minutes: 2100,
      'Pass Accuracy': '86.2%', 'Tackles Won': 38, Interceptions: 22,
      'Prog. Carries/90': 5.4, 'Key Passes/90': 0.7, 'Aerial Duels Won': '48%',
    },
    radarData: [
      { label: 'Speed', value: 65, average: 68 }, { label: 'Passing', value: 78, average: 72 },
      { label: 'Dribbling', value: 58, average: 58 }, { label: 'Physical', value: 72, average: 70 },
      { label: 'Defending', value: 80, average: 74 }, { label: 'Crossing', value: 60, average: 65 },
    ],
    similarPlayers: [
      { playerId: 'p3', name: 'Dani Cortez', club: 'Atlético Ronda', age: 22, similarity: 89, image: '/avatars/player-3.webp' },
      { playerId: 'p6', name: 'Bálint Varga', club: 'Southport City', age: 22, similarity: 84, image: '/avatars/player-6.webp' },
      { playerId: 'p12', name: 'Emre Demir', club: 'Coastal FC', age: 25, similarity: 78, image: '/avatars/player-12.webp' },
    ],
    transferHistory: [
      { club: 'Sporting Castilla', date: 'Jul 2023', fee: '€5.00m' },
      { club: 'Real Sociedad B', date: 'Youth', fee: 'Academy' },
    ],
    contractInfo: { value: '€15.00m', until: 'June 30, 2027', wage: '€38k/week', agent: 'You First Sports' },
  },
  p9: {
    playerId: 'p9',
    playerName: 'Stijn de Graaf',
    age: 24,
    nationality: 'Netherlands',
    position: 'LB / LWB',
    club: 'Harton Villa',
    league: 'Premier League',
    image: '/avatars/player-9.webp',
    summary: 'De Graaf brings a distinctly Dutch approach to the full-back role — technically sound, positionally intelligent, and comfortable receiving the ball in tight spaces. His development at the Ajax academy is evident in his spatial awareness and ability to contribute to build-up play. He has become a regular starter in the Premier League and continues to improve.',
    strengths: [
      'Technical quality on the ball',
      'Spatial awareness in build-up play',
      'Progressive passing from deep',
      'Adaptable to multiple formations',
    ],
    weaknesses: [
      'Can be overpowered in physical duels',
      'Defensive heading needs improvement',
      'Occasionally too slow to release the ball',
    ],
    styleOfPlay: 'A modern, possession-oriented full-back schooled in Dutch positional play. De Graaf operates as a deep playmaker when his team has the ball, stepping inside to create triangles with the midfield. His movement and passing intelligence make him valuable in build-up phases, though he needs protection against direct, physical opponents.',
    recommendation: 'monitor',
    fitScore: 81,
    seasonStats: {
      Appearances: 29, Goals: 1, Assists: 4, Minutes: 2320,
      'Pass Accuracy': '84.8%', 'Tackles Won': 32, Interceptions: 20,
      'Prog. Carries/90': 6.9, 'Key Passes/90': 1.3, 'Aerial Duels Won': '40%',
    },
    radarData: [
      { label: 'Speed', value: 75, average: 68 }, { label: 'Passing', value: 84, average: 72 },
      { label: 'Dribbling', value: 78, average: 58 }, { label: 'Physical', value: 64, average: 70 },
      { label: 'Defending', value: 72, average: 74 }, { label: 'Crossing', value: 70, average: 65 },
    ],
    similarPlayers: [
      { playerId: 'p2', name: 'Enzo Valenti', club: 'Crescent Athletic', age: 23, similarity: 88, image: '/avatars/player-2.webp' },
      { playerId: 'p4', name: 'Tiago Noronha', club: 'AS Lumière', age: 24, similarity: 82, image: '/avatars/player-4.webp' },
      { playerId: 'p11', name: 'Adrien Morel', club: 'AC Stellare', age: 28, similarity: 76, image: '/avatars/player-11.webp' },
    ],
    transferHistory: [
      { club: 'Harton Villa', date: 'Aug 2024', fee: '€9.50m' },
      { club: 'AZ Alkmaar', date: 'Jul 2021', fee: '€2.00m' },
      { club: 'Ajax Youth', date: 'Youth', fee: 'Academy' },
    ],
    contractInfo: { value: '€28.00m', until: 'June 30, 2028', wage: '€58k/week', agent: 'SEG Football' },
  },
  p10: {
    playerId: 'p10',
    playerName: 'Mateo Rivas',
    age: 19,
    nationality: 'Argentina',
    position: 'LB',
    club: 'Miami Coast FC',
    league: 'MLS',
    image: '/avatars/player-10.webp',
    summary: 'Rivas is a raw but exciting teenage prospect who has broken into the Miami Coast first team. At just 19, his physical and technical development is still ongoing. He shows glimpses of exceptional talent — particularly his ability to carry the ball at speed — but his inconsistency and lack of experience are evident. A long-term prospect who could develop into a top-level full-back with the right pathway.',
    strengths: [
      'Explosive pace and acceleration',
      'Natural talent for carrying the ball',
      'Fearless in 1v1 situations',
    ],
    weaknesses: [
      'Defensive awareness is raw',
      'Inconsistent concentration levels',
      'Passing accuracy below required standard',
      'Needs physical development',
    ],
    styleOfPlay: 'A raw, athletic full-back who plays on instinct rather than structure. Rivas is at his best when driving forward with the ball at pace. His defensive game needs significant coaching but his physical attributes and age suggest a high ceiling. Best suited to a development environment with patient coaching.',
    recommendation: 'monitor',
    fitScore: 62,
    seasonStats: {
      Appearances: 14, Goals: 0, Assists: 0, Minutes: 890,
      'Pass Accuracy': '80.5%', 'Tackles Won': 18, Interceptions: 8,
      'Prog. Carries/90': 3.8, 'Key Passes/90': 0.3, 'Aerial Duels Won': '30%',
    },
    radarData: [
      { label: 'Speed', value: 92, average: 68 }, { label: 'Passing', value: 55, average: 72 },
      { label: 'Dribbling', value: 68, average: 58 }, { label: 'Physical', value: 62, average: 70 },
      { label: 'Defending', value: 48, average: 74 }, { label: 'Crossing', value: 50, average: 65 },
    ],
    similarPlayers: [
      { playerId: 'p5', name: 'Rémi Blanchard', club: 'Olympique Azur', age: 23, similarity: 78, image: '/avatars/player-5.webp' },
      { playerId: 'p3', name: 'Dani Cortez', club: 'Atlético Ronda', age: 22, similarity: 65, image: '/avatars/player-3.webp' },
      { playerId: 'p6', name: 'Bálint Varga', club: 'Southport City', age: 22, similarity: 60, image: '/avatars/player-6.webp' },
    ],
    transferHistory: [
      { club: 'Miami Coast FC', date: 'Mar 2026', fee: '€1.80m' },
      { club: 'River Plate Youth', date: 'Youth', fee: 'Academy' },
    ],
    contractInfo: { value: '€5.00m', until: 'Dec 31, 2028', wage: '€12k/week', agent: 'Footfeel ISM' },
  },
  p11: {
    playerId: 'p11',
    playerName: 'Adrien Morel',
    age: 28,
    nationality: 'France',
    position: 'LB / LWB',
    club: 'AC Stellare',
    league: 'Serie A',
    image: '/avatars/player-11.webp',
    summary: 'Morel is a seasoned full-back operating at the peak of his career. His combination of experience, technical quality, and tactical intelligence makes him one of the most complete full-backs in Serie A. He provides consistent high-level performances and is a leader in the dressing room. His age means limited resale value, but his immediate impact would be significant.',
    strengths: [
      'Complete full-back profile — attacks and defends well',
      'Leadership and communication skills',
      'Elite crossing accuracy',
      'Big-game temperament',
      'Fitness and durability',
    ],
    weaknesses: [
      'Age limits long-term value',
      'Declining top speed over long sprints',
      'High wage demands for his age bracket',
    ],
    styleOfPlay: 'A complete, experienced full-back who contributes equally in both phases of play. His positional intelligence means he rarely wastes energy, arriving in the right place at the right time. His crossing accuracy from wide areas is elite — among the top 5% in European football. A plug-and-play signing who would improve most squads immediately.',
    recommendation: 'sign',
    fitScore: 91,
    seasonStats: {
      Appearances: 32, Goals: 2, Assists: 8, Minutes: 2740,
      'Pass Accuracy': '85.9%', 'Tackles Won': 45, Interceptions: 26,
      'Prog. Carries/90': 7.5, 'Key Passes/90': 1.9, 'Aerial Duels Won': '46%',
    },
    radarData: [
      { label: 'Speed', value: 76, average: 68 }, { label: 'Passing', value: 82, average: 72 },
      { label: 'Dribbling', value: 78, average: 58 }, { label: 'Physical', value: 74, average: 70 },
      { label: 'Defending', value: 80, average: 74 }, { label: 'Crossing', value: 88, average: 65 },
    ],
    similarPlayers: [
      { playerId: 'p7', name: 'Samir Benali', club: 'Midland Rovers', age: 23, similarity: 85, image: '/avatars/player-7.webp' },
      { playerId: 'p2', name: 'Enzo Valenti', club: 'Crescent Athletic', age: 23, similarity: 82, image: '/avatars/player-2.webp' },
      { playerId: 'p9', name: 'Stijn de Graaf', club: 'Harton Villa', age: 24, similarity: 78, image: '/avatars/player-9.webp' },
    ],
    transferHistory: [
      { club: 'AC Stellare', date: 'Jul 2022', fee: '€18.00m' },
      { club: 'AS Monaco', date: 'Aug 2018', fee: '€8.50m' },
      { club: 'OGC Nice', date: 'Youth', fee: 'Academy' },
    ],
    contractInfo: { value: '€22.00m', until: 'June 30, 2026', wage: '€120k/week', agent: 'Unique Sports Group' },
  },
  p12: {
    playerId: 'p12',
    playerName: 'Emre Demir',
    age: 25,
    nationality: 'Turkey',
    position: 'LB / RB',
    club: 'Coastal FC',
    league: 'Premier League',
    image: '/avatars/player-12.webp',
    summary: 'Demir is a dependable squad full-back who can cover both flanks competently. His Turkish international experience adds valuable big-game composure. While unlikely to be a first-choice at a top-six club, his versatility, professionalism, and steady performances make him a useful squad player. Offers excellent value relative to his transfer cost.',
    strengths: [
      'Versatility across both flanks',
      'International experience and composure',
      'Strong in aerial duels',
      'Reliable passing accuracy',
    ],
    weaknesses: [
      'Limited ceiling as an attacking full-back',
      'Pace is average for the Premier League',
      'Can be caught flat-footed by quick changes of direction',
    ],
    styleOfPlay: 'A versatile, steady full-back who provides reliable performances without taking risks. Demir is the kind of player who maintains a 7/10 consistently — never the best player on the pitch but rarely the worst. His two-footed ability and tactical flexibility make him valuable as a squad depth option across the back line.',
    recommendation: 'monitor',
    fitScore: 77,
    seasonStats: {
      Appearances: 22, Goals: 0, Assists: 3, Minutes: 1760,
      'Pass Accuracy': '87.1%', 'Tackles Won': 35, Interceptions: 19,
      'Prog. Carries/90': 5.6, 'Key Passes/90': 0.9, 'Aerial Duels Won': '54%',
    },
    radarData: [
      { label: 'Speed', value: 68, average: 68 }, { label: 'Passing', value: 76, average: 72 },
      { label: 'Dribbling', value: 60, average: 58 }, { label: 'Physical', value: 75, average: 70 },
      { label: 'Defending', value: 76, average: 74 }, { label: 'Crossing', value: 62, average: 65 },
    ],
    similarPlayers: [
      { playerId: 'p3', name: 'Dani Cortez', club: 'Atlético Ronda', age: 22, similarity: 85, image: '/avatars/player-3.webp' },
      { playerId: 'p8', name: 'Pablo Navarro', club: 'Sporting Castilla', age: 23, similarity: 82, image: '/avatars/player-8.webp' },
      { playerId: 'p6', name: 'Bálint Varga', club: 'Southport City', age: 22, similarity: 80, image: '/avatars/player-6.webp' },
    ],
    transferHistory: [
      { club: 'Coastal FC', date: 'Aug 2024', fee: '€7.00m' },
      { club: 'Galatasaray', date: 'Jul 2020', fee: '€3.50m' },
      { club: 'Bursaspor', date: 'Youth', fee: 'Academy' },
    ],
    contractInfo: { value: '€16.00m', until: 'June 30, 2028', wage: '€48k/week', agent: 'Promoesport' },
  },
  wp4: {
    playerId: 'wp4',
    playerName: 'Ousmane Diallo',
    age: 28,
    nationality: 'Senegal',
    position: 'CF / LW',
    club: 'Inter Azzurra',
    league: 'Serie A',
    image: '/avatars/player-15.webp',
    summary: 'Diallo is a clinical finisher with explosive acceleration and intelligent movement in the box. His ability to drift wide and cut inside makes him a dual threat as both a striker and inverted winger. Consistently among the top scorers in Serie A over the past three seasons, his off-the-ball runs are elite-level and he excels at finding pockets of space between centre-backs.',
    strengths: [
      'Elite finishing in the box',
      'Explosive acceleration and pace',
      'Intelligent off-the-ball movement',
      'Press-resistant ball retention',
      'Versatility across the front line',
    ],
    weaknesses: [
      'Aerial presence (limited heading ability)',
      'Defensive contribution in pressing phases',
      'Consistency in big matches away from home',
    ],
    styleOfPlay: 'A mobile, direct forward who thrives on running in behind high defensive lines. Diallo combines raw speed with sharp finishing instincts, making him dangerous in transition. When deployed on the left, he drifts centrally to exploit half-spaces. His movement patterns create overloads and pull defenders out of shape.',
    recommendation: 'sign',
    fitScore: 92,
    seasonStats: {
      Appearances: 30, Goals: 16, Assists: 5, Minutes: 2520,
      'Pass Accuracy': '81.4%', 'Tackles Won': 8, Interceptions: 6,
      'Prog. Carries/90': 4.1, 'Key Passes/90': 1.8, 'Aerial Duels Won': '38%',
    },
    radarData: [
      { label: 'Speed', value: 92, average: 65 }, { label: 'Passing', value: 72, average: 70 },
      { label: 'Dribbling', value: 85, average: 60 }, { label: 'Physical', value: 78, average: 72 },
      { label: 'Defending', value: 32, average: 40 }, { label: 'Crossing', value: 58, average: 55 },
    ],
    similarPlayers: [
      { playerId: 'wp5', name: 'Lars Henriksen', club: 'Northgate United', age: 25, similarity: 88, image: '/avatars/player-16.webp' },
      { playerId: 'wp8', name: 'Nicolás Herrera', club: 'AS Roma Rossa', age: 23, similarity: 82, image: '/avatars/player-18.webp' },
      { playerId: 'p11', name: 'Kenji Tanaka', club: 'Coastal FC', age: 28, similarity: 79, image: '/avatars/player-11.webp' },
    ],
    transferHistory: [
      { club: 'Inter Azzurra', date: 'Jul 2022', fee: '€18.00m' },
      { club: 'FC Dakar', date: 'Jan 2019', fee: '€4.50m' },
      { club: 'Génération Foot', date: 'Youth', fee: 'Academy' },
    ],
    contractInfo: { value: '€45.00m', until: 'June 30, 2027', wage: '€120k/week', agent: 'Stellar Group Africa' },
  },
  wp5: {
    playerId: 'wp5',
    playerName: 'Lars Henriksen',
    age: 25,
    nationality: 'Denmark',
    position: 'CF',
    club: 'Northgate United',
    league: 'Premier League',
    image: '/avatars/player-16.webp',
    summary: 'Henriksen is a modern centre-forward who combines physical dominance with technical quality. His hold-up play is among the best in the league, and his ability to bring midfielders into play while also finishing chances makes him a complete striker. Has improved his movement in behind over the past 12 months and is beginning to show consistency at the highest level.',
    strengths: [
      'Elite hold-up play and link-up',
      'Strong aerial presence',
      'Clinical finishing inside the box',
      'Dribbling ability for a striker',
      'Work rate in pressing triggers',
    ],
    weaknesses: [
      'Pace in open-field transitions',
      'Decision-making when isolated on the counter',
      'Left-foot finishing accuracy',
    ],
    styleOfPlay: 'A target striker who excels as a focal point in possession-based systems. Henriksen drops deep to receive, holds defenders off, and plays combination passes before making late runs into the box. His physicality allows him to compete aerially and shield the ball effectively. Best used with pacey wide players who can exploit the space he creates.',
    recommendation: 'monitor',
    fitScore: 85,
    seasonStats: {
      Appearances: 26, Goals: 11, Assists: 7, Minutes: 2210,
      'Pass Accuracy': '78.6%', 'Tackles Won': 12, Interceptions: 4,
      'Prog. Carries/90': 2.8, 'Key Passes/90': 1.2, 'Aerial Duels Won': '68%',
    },
    radarData: [
      { label: 'Speed', value: 62, average: 65 }, { label: 'Passing', value: 74, average: 68 },
      { label: 'Dribbling', value: 78, average: 58 }, { label: 'Physical', value: 88, average: 72 },
      { label: 'Defending', value: 38, average: 40 }, { label: 'Crossing', value: 45, average: 52 },
    ],
    similarPlayers: [
      { playerId: 'wp4', name: 'Ousmane Diallo', club: 'Inter Azzurra', age: 28, similarity: 88, image: '/avatars/player-15.webp' },
      { playerId: 'p11', name: 'Kenji Tanaka', club: 'Coastal FC', age: 28, similarity: 83, image: '/avatars/player-11.webp' },
      { playerId: 'p12', name: 'Tarık Çelik', club: 'Coastal FC', age: 27, similarity: 78, image: '/avatars/player-12.webp' },
    ],
    transferHistory: [
      { club: 'Northgate United', date: 'Aug 2023', fee: '€14.00m' },
      { club: 'FC København', date: 'Jul 2020', fee: '€5.00m' },
      { club: 'Brøndby IF', date: 'Youth', fee: 'Academy' },
    ],
    contractInfo: { value: '€32.00m', until: 'June 30, 2028', wage: '€90k/week', agent: 'Scandinavian Sports Management' },
  },
  wp6: {
    playerId: 'wp6',
    playerName: 'Luca Marchetti',
    age: 26,
    nationality: 'Italy',
    position: 'LB / LWB',
    club: 'Lazio Blu',
    league: 'Serie A',
    image: '/avatars/player-13.webp',
    summary: 'Marchetti is an outstanding progressive ball-carrier from left-back, ranking in the 96th percentile for progressive carries among Serie A defenders. His overlapping runs create numerical advantages in the final third and his crossing delivery is consistently dangerous. Defensively solid in one-on-one situations with excellent recovery pace.',
    strengths: [
      'Elite progressive carrying ability',
      'Crossing accuracy from advanced positions',
      'Recovery speed and defensive transitions',
      'Tactical intelligence in positional play',
      'Set piece delivery',
    ],
    weaknesses: [
      'Aerial duels against taller wingers',
      'Tendency to overcommit in attack',
      'Composure under sustained high press',
    ],
    styleOfPlay: 'An attack-minded wing-back who provides width and depth in the final third. Marchetti is at his best when given license to overlap and deliver crosses into the box. His progressive carrying opens up space for midfielders to exploit. Defensively disciplined enough to play in a back four but thrives in a 3-5-2 or 3-4-3 system.',
    recommendation: 'sign',
    fitScore: 88,
    seasonStats: {
      Appearances: 29, Goals: 2, Assists: 8, Minutes: 2465,
      'Pass Accuracy': '86.8%', 'Tackles Won': 42, Interceptions: 22,
      'Prog. Carries/90': 8.4, 'Key Passes/90': 1.9, 'Aerial Duels Won': '45%',
    },
    radarData: [
      { label: 'Speed', value: 88, average: 68 }, { label: 'Passing', value: 82, average: 72 },
      { label: 'Dribbling', value: 79, average: 58 }, { label: 'Physical', value: 74, average: 70 },
      { label: 'Defending', value: 72, average: 74 }, { label: 'Crossing', value: 85, average: 65 },
    ],
    similarPlayers: [
      { playerId: 'p1', name: 'Marco Lindström', club: 'FC Nordhavn', age: 25, similarity: 92, image: '/avatars/player-1.webp' },
      { playerId: 'p2', name: 'Enzo Valenti', club: 'Crescent Athletic', age: 23, similarity: 87, image: '/avatars/player-2.webp' },
      { playerId: 'wp7', name: 'Alessandro Conti', club: 'Inter Azzurra', age: 28, similarity: 84, image: '/avatars/player-17.webp' },
    ],
    transferHistory: [
      { club: 'Lazio Blu', date: 'Jul 2023', fee: '€12.00m' },
      { club: 'Atalanta', date: 'Jan 2021', fee: '€6.00m' },
      { club: 'Brescia', date: 'Youth', fee: 'Academy' },
    ],
    contractInfo: { value: '€28.00m', until: 'June 30, 2027', wage: '€65k/week', agent: 'GR Sports' },
  },
  wp7: {
    playerId: 'wp7',
    playerName: 'Alessandro Conti',
    age: 28,
    nationality: 'Italy',
    position: 'LWB',
    club: 'Inter Azzurra',
    league: 'Serie A',
    image: '/avatars/player-17.webp',
    summary: 'Conti is a veteran wing-back whose tactical intelligence and reading of the game set him apart. His passing range from deep is exceptional and he orchestrates play from the left flank with calm authority. While not the fastest, his positioning and anticipation make him an effective defender. A reliable, high-floor option for any side playing with wing-backs.',
    strengths: [
      'Exceptional passing range and vision',
      'Tactical awareness and positioning',
      'Key pass delivery into the final third',
      'Leadership and communication on the pitch',
      'Consistency across a full season',
    ],
    weaknesses: [
      'Pace against quick wingers',
      'Recovery speed in transition',
      'Injury history (recurring calf issues)',
    ],
    styleOfPlay: 'A cerebral wing-back who controls tempo from the left side. Conti prefers to receive the ball in deeper zones and pick out teammates with precise through-balls rather than bombing forward. His ability to switch play and find runners in behind with diagonal passes makes him a playmaking option from defence.',
    recommendation: 'monitor',
    fitScore: 90,
    seasonStats: {
      Appearances: 22, Goals: 1, Assists: 6, Minutes: 1870,
      'Pass Accuracy': '91.2%', 'Tackles Won': 28, Interceptions: 30,
      'Prog. Carries/90': 5.6, 'Key Passes/90': 3.1, 'Aerial Duels Won': '50%',
    },
    radarData: [
      { label: 'Speed', value: 65, average: 68 }, { label: 'Passing', value: 92, average: 72 },
      { label: 'Dribbling', value: 70, average: 58 }, { label: 'Physical', value: 72, average: 70 },
      { label: 'Defending', value: 78, average: 74 }, { label: 'Crossing', value: 80, average: 65 },
    ],
    similarPlayers: [
      { playerId: 'wp6', name: 'Luca Marchetti', club: 'Lazio Blu', age: 26, similarity: 84, image: '/avatars/player-13.webp' },
      { playerId: 'p9', name: 'Stijn de Graaf', club: 'Harton Villa', age: 24, similarity: 81, image: '/avatars/player-9.webp' },
      { playerId: 'p7', name: 'Samir Benali', club: 'Midland Rovers', age: 23, similarity: 78, image: '/avatars/player-7.webp' },
    ],
    transferHistory: [
      { club: 'Inter Azzurra', date: 'Jul 2021', fee: '€15.00m' },
      { club: 'Fiorentina', date: 'Aug 2018', fee: '€8.00m' },
      { club: 'Empoli', date: 'Youth', fee: 'Academy' },
    ],
    contractInfo: { value: '€22.00m', until: 'June 30, 2026', wage: '€85k/week', agent: 'Base Soccer Agency' },
  },
  wp8: {
    playerId: 'wp8',
    playerName: 'Nicolás Herrera',
    age: 23,
    nationality: 'Argentina',
    position: 'RW / AM',
    club: 'AS Roma Rossa',
    league: 'Serie A',
    image: '/avatars/player-18.webp',
    summary: 'Herrera is an electrifying attacking talent who has quickly established himself as one of the most exciting young players in Serie A. His dribbling ability and creativity in the final third are outstanding, and he possesses the rare ability to beat defenders in tight spaces. Still developing his end product, but his shot-creating actions per 90 rank among the top 5% in Italy.',
    strengths: [
      'Exceptional dribbling and close control',
      'Shot-creating actions per 90',
      'Acceleration in tight spaces',
      'Creativity and through-ball delivery',
      'Two-footed finishing ability',
    ],
    weaknesses: [
      'End product consistency (shooting accuracy)',
      'Defensive tracking back',
      'Physical duels against stronger defenders',
    ],
    styleOfPlay: 'A flair-driven winger who cuts inside from the right to create and score. Herrera thrives in one-on-one situations and is most dangerous when given the ball in the half-space with room to drive at defenders. His low centre of gravity and quick feet make him almost impossible to dispossess at full speed. Can also operate as a number 10 in more compact systems.',
    recommendation: 'sign',
    fitScore: 87,
    seasonStats: {
      Appearances: 27, Goals: 8, Assists: 9, Minutes: 2160,
      'Pass Accuracy': '83.1%', 'Tackles Won': 14, Interceptions: 8,
      'Prog. Carries/90': 6.2, 'Key Passes/90': 2.4, 'Aerial Duels Won': '28%',
    },
    radarData: [
      { label: 'Speed', value: 90, average: 68 }, { label: 'Passing', value: 80, average: 70 },
      { label: 'Dribbling', value: 94, average: 60 }, { label: 'Physical', value: 58, average: 68 },
      { label: 'Defending', value: 28, average: 38 }, { label: 'Crossing', value: 72, average: 62 },
    ],
    similarPlayers: [
      { playerId: 'wp4', name: 'Ousmane Diallo', club: 'Inter Azzurra', age: 28, similarity: 82, image: '/avatars/player-15.webp' },
      { playerId: 'p4', name: 'Tiago Noronha', club: 'AS Lumière', age: 24, similarity: 80, image: '/avatars/player-4.webp' },
      { playerId: 'wp11', name: 'Tomás Ferreira', club: 'Vitória Guimarães B', age: 18, similarity: 76, image: '/avatars/player-20.webp' },
    ],
    transferHistory: [
      { club: 'AS Roma Rossa', date: 'Jan 2025', fee: '€9.00m' },
      { club: 'Racing Club', date: 'Jul 2022', fee: '€3.00m' },
      { club: 'Argentinos Juniors', date: 'Youth', fee: 'Academy' },
    ],
    contractInfo: { value: '€35.00m', until: 'June 30, 2029', wage: '€55k/week', agent: 'Gestifute South America' },
  },
  wp10: {
    playerId: 'wp10',
    playerName: 'Jakub Nowicki',
    age: 17,
    nationality: 'Poland',
    position: 'CM',
    club: 'Wisła Kraków',
    league: 'Ekstraklasa',
    image: '/avatars/player-19.webp',
    summary: 'Nowicki is a prodigiously talented central midfielder who has broken into Wisła Kraków\'s first team at just 17. His vision and passing ability are far beyond his years, and his composure on the ball in tight situations is remarkable for a player of his age. Still physically developing but his technical foundation and football intelligence suggest an extremely high ceiling.',
    strengths: [
      'Exceptional vision and passing range',
      'Composure under pressure',
      'Ball retention in midfield',
      'Progressive passing and carrying',
      'Football intelligence and spatial awareness',
    ],
    weaknesses: [
      'Physical development (still growing)',
      'Defensive intensity and aggression',
      'Stamina over 90 minutes',
    ],
    styleOfPlay: 'A deep-lying playmaker who dictates the tempo of the game from central midfield. Nowicki receives between the lines, turns, and finds forward passes with uncanny regularity. His first touch is immaculate and he uses body feints to create space before threading balls into dangerous areas. Needs a physical partner alongside him to compensate for his developing frame.',
    recommendation: 'monitor',
    fitScore: 71,
    seasonStats: {
      Appearances: 18, Goals: 2, Assists: 4, Minutes: 1120,
      'Pass Accuracy': '90.4%', 'Tackles Won': 16, Interceptions: 14,
      'Prog. Carries/90': 3.2, 'Key Passes/90': 2.8, 'Aerial Duels Won': '32%',
    },
    radarData: [
      { label: 'Speed', value: 58, average: 62 }, { label: 'Passing', value: 88, average: 68 },
      { label: 'Dribbling', value: 76, average: 55 }, { label: 'Physical', value: 48, average: 65 },
      { label: 'Defending', value: 52, average: 60 }, { label: 'Crossing', value: 60, average: 55 },
    ],
    similarPlayers: [
      { playerId: 'wp11', name: 'Tomás Ferreira', club: 'Vitória Guimarães B', age: 18, similarity: 80, image: '/avatars/player-20.webp' },
      { playerId: 'p10', name: 'Mateo Rivas', club: 'Miami Coast FC', age: 19, similarity: 76, image: '/avatars/player-10.webp' },
      { playerId: 'p4', name: 'Tiago Noronha', club: 'AS Lumière', age: 24, similarity: 72, image: '/avatars/player-4.webp' },
    ],
    transferHistory: [
      { club: 'Wisła Kraków', date: 'Youth', fee: 'Academy' },
    ],
    contractInfo: { value: '€5.00m', until: 'June 30, 2029', wage: '€8k/week', agent: 'Unrepresented' },
  },
  wp11: {
    playerId: 'wp11',
    playerName: 'Tomás Ferreira',
    age: 18,
    nationality: 'Portugal',
    position: 'RW',
    club: 'Vitória Guimarães B',
    league: 'Liga Portugal 2',
    image: '/avatars/player-20.webp',
    summary: 'Ferreira is a rapid, direct winger who has caught the attention of several top-flight clubs with his performances for Vitória\'s B team. His ability to beat defenders with pace and skill is already at a high level, and his end product is developing rapidly. At 18, he offers significant upside and could develop into a top-tier wide forward with the right coaching environment.',
    strengths: [
      'Explosive pace and acceleration',
      'One-on-one dribbling success rate',
      'Direct running and ball progression',
      'Confidence and fearlessness on the ball',
      'Improving end product (goals + assists trending up)',
    ],
    weaknesses: [
      'Decision-making in the final third',
      'Defensive awareness and tracking',
      'Consistency across matches',
    ],
    styleOfPlay: 'A touchline-hugging winger who loves to receive the ball in wide areas and take on his full-back directly. Ferreira uses his electric pace to get to the byline and deliver crosses, or cuts inside onto his left foot to shoot. His directness stretches opposition defences and creates space for others. Still learning when to release the ball versus when to carry it.',
    recommendation: 'monitor',
    fitScore: 68,
    seasonStats: {
      Appearances: 22, Goals: 6, Assists: 5, Minutes: 1540,
      'Pass Accuracy': '79.2%', 'Tackles Won': 10, Interceptions: 6,
      'Prog. Carries/90': 5.8, 'Key Passes/90': 1.6, 'Aerial Duels Won': '25%',
    },
    radarData: [
      { label: 'Speed', value: 94, average: 68 }, { label: 'Passing', value: 65, average: 66 },
      { label: 'Dribbling', value: 86, average: 58 }, { label: 'Physical', value: 55, average: 62 },
      { label: 'Defending', value: 25, average: 35 }, { label: 'Crossing', value: 70, average: 58 },
    ],
    similarPlayers: [
      { playerId: 'wp8', name: 'Nicolás Herrera', club: 'AS Roma Rossa', age: 23, similarity: 76, image: '/avatars/player-18.webp' },
      { playerId: 'wp10', name: 'Jakub Nowicki', club: 'Wisła Kraków', age: 17, similarity: 72, image: '/avatars/player-19.webp' },
      { playerId: 'p10', name: 'Mateo Rivas', club: 'Miami Coast FC', age: 19, similarity: 70, image: '/avatars/player-10.webp' },
    ],
    transferHistory: [
      { club: 'Vitória Guimarães B', date: 'Youth', fee: 'Academy' },
    ],
    contractInfo: { value: '€3.50m', until: 'June 30, 2028', wage: '€5k/week', agent: 'Gestifute' },
  },
  wp12: {
    playerId: 'wp12',
    playerName: 'K. Papadopoulos',
    age: 21,
    nationality: 'Greece',
    position: 'LB/CB',
    club: 'Olympique Azur',
    league: 'Ligue 1',
    image: '/avatars/player-14.webp',
    summary: 'Papadopoulos is a versatile young defender who can operate comfortably at left-back or centre-back. His reading of the game and composure on the ball belie his age, and he has quickly established himself as a starter in Ligue 1. An injury concern has emerged recently, but when fit he is one of the most promising defensive talents in France.',
    strengths: [
      'Excellent positional awareness',
      'Composed ball-playing from the back',
      'Strong in aerial duels for his age',
      'Versatility across defensive positions',
      'Progressive passing ability',
    ],
    weaknesses: [
      'Pace in recovery runs',
      'Recent injury concerns',
      'Can be caught out by quick wingers',
    ],
    styleOfPlay: 'A calm, ball-playing defender who prefers to build from the back rather than go long. Papadopoulos positions himself well to intercept and uses his passing range to start attacks. At left-back, he provides reliable overlap runs and accurate crosses. His defensive intelligence compensates for a lack of explosive pace.',
    recommendation: 'monitor',
    fitScore: 82,
    seasonStats: {
      Appearances: 24, Goals: 1, Assists: 3, Minutes: 2040,
      'Pass Accuracy': '89.4%', 'Tackles Won': 48, Interceptions: 32,
      'Prog. Carries/90': 3.2, 'Key Passes/90': 0.8, 'Aerial Duels Won': '68%',
    },
    radarData: [
      { label: 'Speed', value: 62, average: 68 }, { label: 'Passing', value: 80, average: 66 },
      { label: 'Dribbling', value: 55, average: 58 }, { label: 'Physical', value: 74, average: 62 },
      { label: 'Defending', value: 82, average: 65 }, { label: 'Crossing', value: 65, average: 58 },
    ],
    similarPlayers: [
      { playerId: 'p2', name: 'Enzo Valenti', club: 'Crescent Athletic', age: 23, similarity: 78, image: '/avatars/player-2.webp' },
      { playerId: 'p3', name: 'Dani Cortez', club: 'Atlético Ronda', age: 22, similarity: 74, image: '/avatars/player-3.webp' },
      { playerId: 'p6', name: 'Bálint Varga', club: 'Southport City', age: 22, similarity: 71, image: '/avatars/player-6.webp' },
    ],
    transferHistory: [
      { club: 'Olympiakos Youth', date: '2020', fee: 'Academy' },
      { club: 'Olympique Azur', date: '2024', fee: '€4.5m' },
    ],
    contractInfo: { value: '€8.00m', until: 'June 30, 2028', wage: '€25k/week', agent: 'Wasserman' },
  },
}
